### ISSUE TITLE
MMS sending (and receiving) fails if on WiFi and APN is set to IPv6

### ISSUE THREAD

**Issue by apmon** [WhisperSystems/TextSecure#1937]
Hello,

I am having trouble sending and receiving MMS on my T-Mobile USA Samsung galaxy S4 (Android 4.4.4) while connected to WiFi. I am using TextSecure 2.1.8.

It looks like the problems have something to do with the switch from IPv4 (on WiFi) to IPv6 on the cellular network.

If I manually disable WiFi and send a MMS through TextSecure on the IPv6 only APN, the MMS is correctly sent and received.

If I manually switch the APN to IPv4 only, then TextSecure correctly sends and receives MMS while connected to WiFi (by transitioning to the cellular network to send the MMS).

However, if I use the default APN of the phone (IPv6 only) and I am connected to the IPv4 only WiFi, sending fails. The logs show that TextSecure attempts to connect to the cellular, but then times out connecting to the MMSC (2607:7700:0:5::ab8:4b81) because of Network unreachable.

**Comment by apmon** [comment]
@konklone Thanks for confirming.

Although I actually meant something slightly differently. I was wondering if the new Connectivity APIs in Android 5 allow to solve this issue. So you will need to rewrite some code to test this, and therefore the devs (@mcginty ?) will need to try this out at some point. (I don't have an Android 5 phone and I haven't yet tried to compile TextSecure myself, so I can't do this).

**Comment by mcginty** [comment]
I tested the Android 5 MMS APIs and it solves both IPv6 and Wi-Fi issues on Lollipop. Good news, will have something out soon for that.

**Comment by apmon** [comment]
Oh great!

Now we only need to wait for a couple of years until people's phone are actually running Lollipop... ;-)

**Comment by jeremymasters** [comment]
@apmon I think he meant he will have a fix for earlier android too.  @mcginty are we slated for a release sometime soon?

**Comment by johnrandolph** [comment]
so does the fix bind to the cell interface when it sees internal reserved IPs resolved for the mms server, or...? seeing the same problem here, nexus 5 stock 4.4.4 on wifi, the DNS lookup of tmobile mms server answer is 10.x which of course can't be reached over any network but tmobile... etc..

**Comment by Adalan** [comment]
@mcginty, any idea when the possible fix will roll out?

**Comment by mcginty** [comment]
@Adalan slated for 2.7.0

**Comment by Adalan** [comment]
Awesome, thanks for the reply (and obvious hard work).

**Comment by cmherna7** [comment]
So how do I fix?

**Comment by Adalan** [comment]
It doesn't appear to be fixed yet. On WiFi, I still can't send or receive
MMS messages.

**Comment by cmherna7** [comment]
If you search on google play for an app that willl switch the apn away from
LTE, that should give you a temporary fix until the issue is solved.

On Mon, Mar 23, 2015 at 3:05 AM, Adam Landry <notifications@github.com>
wrote:

> It doesn't appear to be fixed yet. On WiFi, I still can't send or receive
> MMS messages.
> On Mar 22, 2015 11:03 PM, "cmherna7" <notifications@github.com> wrote:
>
> > So how do I fix?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/WhisperSystems/TextSecure/issues/1937#issuecomment-84767917
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/TextSecure/issues/1937#issuecomment-84925399>
> .
>



-- 

_______________________________
Cameron Hernandez

Mobile: 309-838-7639

**Comment by Adalan** [comment]
I found messing with my APN's did nothing to solve the problem and
introduced weird service issues. I simply disconnect from wifi when I need
to read or send an MMS.

**Comment by cmherna7** [comment]
Same here.

On Mon, Mar 23, 2015 at 10:46 AM, Adam Landry <notifications@github.com>
wrote:

> I found messing with my APN's did nothing to solve the problem and
> introduced weird service issues. I simply disconnect from wifi when I need
> to read or send an MMS.
>
> On Mon, Mar 23, 2015 at 1:44 PM, cmherna7 <notifications@github.com>
> wrote:
>
> > If you search on google play for an app that willl switch the apn away
> from
> > LTE, that should give you a temporary fix until the issue is solved.
> >
> > On Mon, Mar 23, 2015 at 3:05 AM, Adam Landry <notifications@github.com>
> > wrote:
> >
> >
> > > It doesn't appear to be fixed yet. On WiFi, I still can't send or
> receive
> > > MMS messages.
> > > On Mar 22, 2015 11:03 PM, "cmherna7" <notifications@github.com> wrote:
> > >
> > > > So how do I fix?
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/WhisperSystems/TextSecure/issues/1937#issuecomment-84767917
> > > >
> > > > .
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/WhisperSystems/TextSecure/issues/1937#issuecomment-84925399
> > >
> > > .
> > >
> >
> >
> >
> > --
> >
> > _______________________________
> > Cameron Hernandez
> >
> > Mobile: 309-838-7639
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/WhisperSystems/TextSecure/issues/1937#issuecomment-85120942
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/TextSecure/issues/1937#issuecomment-85121452>
> .
>



-- 

_______________________________
Cameron Hernandez

Mobile: 309-838-7639

**Comment by apmon** [comment]
Thank you for fixing this. Is this a lollipop only fix though? Or is it just fixed differently on Lollipop and prior versions?

**Comment by moxie0** [comment]
It's lollipop only.  I don't think it's possible to make this work on older version of Android, since the routing API doesn't accept IPv6 addresses.

**Comment by mcginty** [comment]
@apmon, there was a hidden IPv6 routing API that Android had in previous versions, but it didn't seem to work when I implemented and tested it. Unless something comes up to show otherwise, I think this bug is only resolvable in Lollipop and above.

**Comment by manojka** [comment]
What do the built-in clients do? (I'm on Lollipop so this fix will be plenty for me, but I am curious.)

**Comment by Adalan** [comment]
I'm still having the same issues.
https://gist.github.com/018fc8f84beb8231ced8

**Comment by moxie0** [comment]
@Adalan You're not running the release with the fix.

**Comment by Adalan** [comment]
Well that would do it. Sorry for the spam.

**Comment by moxie0** [comment]
@Adalan The README.md contains instructions for joining the beta if you want early access to releases.

**Comment by Adalan** [comment]
Bingo, that was the confusion. I could have sworn that I was already on the
beta. Either way, 2.9.0 is allowing me to send and receive MMS on Wifi.

Thanks for all the work.

On Thu, Mar 26, 2015 at 7:20 PM, Moxie Marlinspike <notifications@github.com

**Comment by mcginty** [comment]
Great news, thanks for reporting back @Adalan
