### ISSUE TITLE
notification unread message when locking textsecure 

### ISSUE THREAD

**Issue by watermeloen** [WhisperSystems/TextSecure#2287]
Evertytime I lock TextSecure I get a notification about an unread message from a certain contact (always the same contact), but it is wrong as I already have read all messages.

**Comment by n1m1** [comment]
Same problem here. Moreover, if I end the secure session with that particular contact I can't begin a new one, because when I tap the monitor to terminate the key exchange nothing happens.

**Comment by watermeloen** [comment]
One more thing, everytime I receive a new sms message, I get a notification about two new messages, although there is only one actually. The other "new" message is from the above mentioned contact, a message which I have already read.

**Comment by n1m1** [comment]
Yes. I confirm also this: it happens the same on my phone.

**Comment by n1m1** [comment]
The issue seems solved in 2.4.1

**Comment by watermeloen** [comment]
The issue is still not solved for me, using the latest version. If I lock the app I receive a notification about a "new" message, which is not correct, there are no new messages.

**Comment by zmanian** [comment]
I'm observing this issue as well on TS 2.4.2, Nexus 5, Lollipop, stock. Two old message notifications  appear when TS locks.. Interestingly these aren't the most recent messages.

**Comment by jeremymasters** [comment]
Is there a chance that using an app like lightflow to clear notifications could at least alleviate this temporarily for users?

**Comment by n1m1** [comment]
I apologize for my previous mistake. Indeed the issue is NOT solved. Right now, I'm again able to terminate the exchange key but the "double notification" still appears randomly with the same contact. Lp, non-stock rom. 

Once again, sorry for the previous wrong report.

**Comment by eX00r** [comment]
Same here. Keep getting "unread Message(s)" notice from the same contact although there is no unread message.

**Comment by McLoo** [comment]
related to #2358 i guess

**Comment by nwdev** [comment]
Same issue here.

Droid Razr M - Android 4.4.2
TextSecure 2.4.2

**Comment by shaaati** [comment]
I can confirm the issue with the latest Textsecure version (2.5.1) on Nexus 5, Android 5.0.1.
As an additional note: The notification just silently pops up at random. It does not trigger a vibration or ringtone as a real incoming message would do.

**Comment by zmanian** [comment]
@shaaati 
The stuck unread notification pops up every time the passphrase is removed from memory.

This happens either when the timer passphrase expires or if the TextSecure background notification process is restarted. This happens somewhat randomly because of memory management issues in Android 5.0.*

The same 2 unread notifications have been stuck in my notifications since shortly after the 2.4 upgrade. 

Another  observation is when a new message from one of those users comes in I see a double notification for the same user in notification window.

**Comment by spoesel** [comment]
Same issue as described by zmanian. unread notifications from the same 2 users, and only from them, after password is removed from memory. From at least one of them i never received at least one sent push message.

LGE Optimus 4X hd 
cyanogenmod cm_p880 - userdebug 4.4.4 KTU84Q
TextSecure 2.5.3

**Comment by McLoo** [comment]
hey guys, would you mind to answer how you mark the messages as unread? Please add the information over in #2358

**Comment by shaaati** [comment]
New details: Since upgrading to 2.6.0 I have another unread notification that now pops up.
The second one comes from the same account as the first one, but that might just be a coincidence.
I can tell that the notification comes from a group message of this specific contact that was unread while upgrading to the new version. After upgrading and unlocking TS I cannot see the message in the group while other users can.

**Comment by McLoo** [comment]
@shaaati thanks for the details!
Hey @moxie0 the issue seems pretty narrowed down now. (Though the main information is in #2358)
What about some backup timer, that picks up abandoned entries in the push table?

**Comment by moxie0** [comment]
@shaaati Thanks for the updates, narrowing down the actual message is useful.

@McLoo It's true that inserting something into the push DB and queuing the decrypt job are not a single atomic operation, so there's a very slight race condition which will leave users in a bad state if the app is killed in between those two operations.

Unfortunately the solution is not entirely straightforward.  There's not really any sane way to know whether a job is already queued for an existing message id or not.  Instead, we should probably focus on making that operation atomic somehow.

**Comment by zmanian** [comment]
Previously discussed in #2392

**Comment by zmanian** [comment]
I'm up to three unread message notifications when the device is locked. 

 I'm willing to clear app data to see if it resolves the behavior if that would help.

Let me know what I can do to help.

**Comment by McLoo** [comment]
@zmanian clearing the app data should help remove the ghosts. It's not needed for further clarification right now.
But if you can live with them, I bed @moxie0 is going to add a one-time-pre 
-atomic-fix?! That way you could keep all data.

**Comment by drohhyn** [comment]
Something new for me (older ticket was #2404): When I keep using the phone and textsecure locks (after 10min in my setup), it comes up with the passphrase login on the screen no matter which application is in use right now.
This does not happen on another device where no "ghost message" appears.

**Comment by shaaati** [comment]
@drohhyn I don't know where, but I'm pretty certain that there is another ticket talking about that problem.

**Comment by McLoo** [comment]
@drohhyn you're on Android 5+ ?

**Comment by drohhyn** [comment]
Yes, on a nexus 5 with stock Android 5.0.1 

Am 10. März 2015 19:01:46 MEZ, schrieb McLoo <notifications@github.com>:
>@drohhyn you're on Android 5+ ?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/WhisperSystems/TextSecure/issues/2287#issuecomment-78111282

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by McLoo** [comment]
@drohhyn you're most likely hit by #2239 too - in addition to this one.

**Comment by McLoo** [comment]
@moxie0 new milestone 2.9.0?
