### ISSUE TITLE
MMS Messaging not working

### ISSUE THREAD

**Issue by biscuitgod** [WhisperSystems/TextSecure#3103]
Just upgraded my OnePlus One phone to CM12 (Android Lollipop 5.02)...  I have ATT Service and not able to receive or send MMS messages.  App is up to date and everything worked prior to upgrade.  I do still receive Secure messages from other TextSecure users and non-secure txt works from non TextSecure users.  Only MMS is the issue.  

debug logs:  https://gist.github.com/0a049940905944f1ee75

This issue looks similar to #3019 and #3057

**Comment by pklime2** [comment]
Same issue here.  Upgraded to CM12 on my OnePlus One last night and MMS no longer works in TextSecure.  The default Messaging app for CM12 can send/receive MMS messages after enabling the "Auto-enable data - Automatically enable mobile data for MMS messages" option.

Also an AT&T subscriber.

**Comment by redragonx** [comment]
I have the same issue on the M8. I also cannot see the MMS setting option anymore in Android L. Is this supposed to happen?

Carrier: VZW 
Android: 5.0.1 (ViperOne M8 4.3.0)
Log: https://gist.github.com/anonymous/3a724c835e7681ab2e64

**Comment by mcginty** [comment]
@biscuitgod  @pklime2 2.14 changed the MMS behavior. Can you let me know if it works now?

**Comment by biscuitgod** [comment]
still not working here!

**Comment by redragonx** [comment]
@mcginty I updated to 2.14 and MMS is working now. Thank you!

**Comment by mcginty** [comment]
@biscuitgod can you post a new debug log now that you're on 2.14?

@redragonx good to hear :)

**Comment by biscuitgod** [comment]
Here's new debug log:  https://gist.github.com/46f796c15f86dcb9083b

On May 18, 2015 9:24 PM, Jake McGinty <notifications@github.com> wrote:

@biscuitgod<https://github.com/biscuitgod> can you post a new debug log now that you're on 2.14?

@redragonx<https://github.com/redragonx> good to hear :)

**Comment by mcginty** [comment]
Thanks, @biscuitgod 

```
W/LegacyMmsConnection(26623): * response code: HTTP/1.1 403 Invalid MSISDN number received.
W/OutgoingLegacyMmsConnection(26623): java.io.IOException: unhandled response code
W/OutgoingLegacyMmsConnection(26623): 	at org.thoughtcrime.securesms.mms.LegacyMmsConnection.execute(LegacyMmsConnection.java:193)
W/OutgoingLegacyMmsConnection(26623): 	at org.thoughtcrime.securesms.mms.OutgoingLegacyMmsConnection.sendBytes(OutgoingLegacyMmsConnection.java:135)
W/OutgoingLegacyMmsConnection(26623): 	at org.thoughtcrime.securesms.mms.OutgoingLegacyMmsConnection.send(OutgoingLegacyMmsConnection.java:118)
W/OutgoingLegacyMmsConnection(26623): 	at org.thoughtcrime.securesms.mms.OutgoingLegacyMmsConnection.send(OutgoingLegacyMmsConnection.java:101)
W/OutgoingLegacyMmsConnection(26623): 	at org.thoughtcrime.securesms.mms.CompatMmsConnection.send(CompatMmsConnection.java:39)
W/OutgoingLegacyMmsConnection(26623): 	at org.thoughtcrime.securesms.jobs.MmsSendJob.onSend(MmsSendJob.java:72)
W/OutgoingLegacyMmsConnection(26623): 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:39)
W/OutgoingLegacyMmsConnection(26623): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
W/OutgoingLegacyMmsConnection(26623): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
W/OutgoingLegacyMmsConnection(26623): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
W/OutgoingLegacyMmsConnection(26623): java.io.IOException: Connection manager could not obtain route to host.
W/OutgoingLegacyMmsConnection(26623): 	at org.thoughtcrime.securesms.mms.OutgoingLegacyMmsConnection.sendBytes(OutgoingLegacyMmsConnection.java:141)
W/OutgoingLegacyMmsConnection(26623): 	at org.thoughtcrime.securesms.mms.OutgoingLegacyMmsConnection.send(OutgoingLegacyMmsConnection.java:118)
W/OutgoingLegacyMmsConnection(26623): 	at org.thoughtcrime.securesms.mms.OutgoingLegacyMmsConnection.send(OutgoingLegacyMmsConnection.java:101)
W/OutgoingLegacyMmsConnection(26623): 	at org.thoughtcrime.securesms.mms.CompatMmsConnection.send(CompatMmsConnection.java:39)
W/OutgoingLegacyMmsConnection(26623): 	at org.thoughtcrime.securesms.jobs.MmsSendJob.onSend(MmsSendJob.java:72)
W/OutgoingLegacyMmsConnection(26623): 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:39)
W/OutgoingLegacyMmsConnection(26623): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
W/OutgoingLegacyMmsConnection(26623): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
W/OutgoingLegacyMmsConnection(26623): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
```

**Comment by moxie0** [comment]
@mcginty It also looks like once that fails, it doesn't fallback to the lollipop api?

**Comment by mcginty** [comment]
@moxie0 it falls back, that's further down in the log. Timeout exception.

**Comment by pklime2** [comment]
Here is one more log for you, I just tested and looks like the same error.

https://gist.github.com/anonymous/2fad0cb16e7a698070d5

**Comment by mcginty** [comment]
Yeah, so it looks like the proxy used with that APN config rejects the incoming connection, then when we try to connect without a proxy we get this MSISDN error (even though we do submit an MSISDN header if a phone number is available).

Will investigate more.

**Comment by mcginty** [comment]
Thanks for the log, @pklime2, that does look like the same error.

**Comment by trogdoor17** [comment]
I also wanted to submit a debug log after encountering this error.
https://gist.github.com/anonymous/06361e31d15a8cd97e68

**Comment by keleathi** [comment]
I'm on 2.21 also on an ATT OnePlus One running CM12, and MMS fails.  My debug log is at:  https://gist.github.com/8d67350ab7210900a891

Any thoughts would be very appreciated; I love the app and hate going back to the stock SMS.

**Comment by jeremymasters** [comment]
@keleathi the software is now on 2.24.1.  It would be a good idea to update and see if the problem persists too.

**Comment by biscuitgod** [comment]
?doesn't appear the new 2.24.1 version is still working for me...


guess it's back to stock again.

________________________________

**Comment by eosrei** [comment]
@biscuitgod @keleathi  Please check the regular (previous) fix for this issue: Temporarily disable Wi-Fi. I've had this specific issue since originally installing TextSecure, but it's been fixed in recent versions.

**Comment by keleathi** [comment]
@jeremymasters - As soon as I posted, I thought to look for an update and installed it.  I'm still having the same issue.

@eosrei - I'm not on wifi when having the issue; I'm on LTE.  Though now that you mention it, I just tried and I also have the problem on my wifi network as well.

**Comment by lukedupin** [comment]
https://gist.github.com/e595687ea01e3a7a54f2

I'm having slow mms downloads or failed to download.  3.7.2. Anything I can try?

**Comment by nwbt** [comment]
With US AT&T I had the same issue with a Moto X (1st gen) Android 5.1.

Settings > Cellular Networks > Access Point Names > Reset to Default ... Fixed the issue for the time being.

There was another APN which handled MMS listed before I selected Reset to Default. After "Reset to Default" was selected the second APN for AT&T was removed and now MMS pictures download with no problem.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
