### ISSUE TITLE
JSON or server related crash on first textsecure message?

### ISSUE THREAD

**Issue by kainz** [WhisperSystems/TextSecure#3827]
Log: 
```
W/JobConsumer(12122): org.whispersystems.textsecure.internal.util.JsonUtil$JsonParseException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
W/JobConsumer(12122):  at [Source: <html>
W/JobConsumer(12122): <head><title>411 Length Required</title></head>
W/JobConsumer(12122): <body bgcolor="white">
W/JobConsumer(12122): <center><h1>411 Length Required</h1></center>
W/JobConsumer(12122): <hr><center>nginx/1.1.19</center>
W/JobConsumer(12122): </body>
W/JobConsumer(12122): </html>
W/JobConsumer(12122): ; line: 1, column: 2]
W/JobConsumer(12122): 	at org.whispersystems.textsecure.internal.util.JsonUtil.fromJson(JsonUtil.java:44)
W/JobConsumer(12122): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.makeBaseRequest(PushServiceSocket.java:523)
W/JobConsumer(12122): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.makeRequest(PushServiceSocket.java:465)
W/JobConsumer(12122): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.sendMessage(PushServiceSocket.java:169)
W/JobConsumer(12122): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:300)
W/JobConsumer(12122): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:123)
W/JobConsumer(12122): 	at org.thoughtcrime.securesms.jobs.PushTextSendJob.deliver(PushTextSendJob.java:115)
W/JobConsumer(12122): 	at org.thoughtcrime.securesms.jobs.PushTextSendJob.onSend(PushTextSendJob.java:62)
W/JobConsumer(12122): 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:40)
W/JobConsumer(12122): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
W/JobConsumer(12122): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
W/JobConsumer(12122): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
W/JobConsumer(12122): Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
W/JobConsumer(12122):  at [Source: <html>
W/JobConsumer(12122): <head><title>411 Length Required</title></head>
W/JobConsumer(12122): <body bgcolor="white">
W/JobConsumer(12122): <center><h1>411 Length Required</h1></center>
W/JobConsumer(12122): <hr><center>nginx/1.1.19</center>
W/JobConsumer(12122): </body>
W/JobConsumer(12122): </html>
W/JobConsumer(12122): ; line: 1, column: 2]
W/JobConsumer(12122): 	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1486)
W/JobConsumer(12122): 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518)
W/JobConsumer(12122): 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:447)
W/JobConsumer(12122): 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1462)
W/JobConsumer(12122): 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:683)
W/JobConsumer(12122): 	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3600)
W/JobConsumer(12122): 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3545)
W/JobConsumer(12122): 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2576)
W/JobConsumer(12122): 	at org.whispersystems.textsecure.internal.util.JsonUtil.fromJson(JsonUtil.java:41)
W/JobConsumer(12122): 	... 11 more
E/AndroidRuntime(12122): FATAL EXCEPTION: JobConsumer-2
E/AndroidRuntime(12122): Process: org.thoughtcrime.securesms, PID: 12122
E/AndroidRuntime(12122): org.whispersystems.textsecure.internal.util.JsonUtil$JsonParseException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
E/AndroidRuntime(12122):  at [Source: <html>
E/AndroidRuntime(12122): <head><title>411 Length Required</title></head>
E/AndroidRuntime(12122): <body bgcolor="white">
E/AndroidRuntime(12122): <center><h1>411 Length Required</h1></center>
E/AndroidRuntime(12122): <hr><center>nginx/1.1.19</center>
E/AndroidRuntime(12122): </body>
E/AndroidRuntime(12122): </html>
E/AndroidRuntime(12122): ; line: 1, column: 2]
E/AndroidRuntime(12122): 	at org.whispersystems.textsecure.internal.util.JsonUtil.fromJson(JsonUtil.java:44)
E/AndroidRuntime(12122): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.makeBaseRequest(PushServiceSocket.java:523)
E/AndroidRuntime(12122): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.makeRequest(PushServiceSocket.java:465)
E/AndroidRuntime(12122): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.sendMessage(PushServiceSocket.java:169)
E/AndroidRuntime(12122): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:300)
E/AndroidRuntime(12122): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:123)
E/AndroidRuntime(12122): 	at org.thoughtcrime.securesms.jobs.PushTextSendJob.deliver(PushTextSendJob.java:115)
E/AndroidRuntime(12122): 	at org.thoughtcrime.securesms.jobs.PushTextSendJob.onSend(PushTextSendJob.java:62)
E/AndroidRuntime(12122): 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:40)
E/AndroidRuntime(12122): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
E/AndroidRuntime(12122): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
E/AndroidRuntime(12122): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
E/AndroidRuntime(12122): Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
E/AndroidRuntime(12122):  at [Source: <html>
E/AndroidRuntime(12122): <head><title>411 Length Required</title></head>
E/AndroidRuntime(12122): <body bgcolor="white">
E/AndroidRuntime(12122): <center><h1>411 Length Required</h1></center>
E/AndroidRuntime(12122): <hr><center>nginx/1.1.19</center>
E/AndroidRuntime(12122): </body>
E/AndroidRuntime(12122): </html>
E/AndroidRuntime(12122): ; line: 1, column: 2]
E/AndroidRuntime(12122): 	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1486)
E/AndroidRuntime(12122): 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518)
E/AndroidRuntime(12122): 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:447)
E/AndroidRuntime(12122): 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1462)
E/AndroidRuntime(12122): 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:683)
E/AndroidRuntime(12122): 	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3600)
E/AndroidRuntime(12122): 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3545)
E/AndroidRuntime(12122): 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2576)
E/AndroidRuntime(12122): 	at org.whispersystems.textsecure.internal.util.JsonUtil.fromJson(JsonUtil.java:41)
E/AndroidRuntime(12122): 	... 11 more
W/ActivityManager(  923):   Force finishing activity 1 org.thoughtcrime.securesms/.RoutingActivity
```

Going back a bit earlier in my log this looks like its from the initial push message for outputting a secret to a new textsecure user, like the following:
```
W/PushServiceSocket(12122): PUT  --  {"destination":"+PHONENUMBERREDACTED","messages":[{"body":"Iwjb9ZIEEiEF5lAlBWYYcX7xNIEDK44BfQU530t7YR+XgXMbdKQeOCwaIQWx1/lRWPKNw4f/UtSo14iNlGl5dfGGYXENPzNLue15PSJCIwohBbkY84xJxW7jyXoCgcr3gG2C5B5tNQs5R9zK/bou5648EBMYACIQwsLQZJarLNQm125mnA5iVgRnkTjZQQ9OKNcRMP////8P","content":null,"destinationDeviceId":1,"destinationRegistrationId":0,"type":3}],"relay":"cyanogen","timestamp":1438055562341}
```

Fresh textsecure install, registered/keys generated, but no passwords or the like setup.  Crash is triggered when I send a message to another textsecure user.

This is with TextSecure 2.23.2 on Android 5.1 (moto x 2014).

**Comment by moxie0** [comment]
Can you please include the full log? Can't make out what's going on from this snip.

**Comment by moxie0** [comment]
should be fixed

**Comment by kainz** [comment]
@moxie0 still happens on 2.23.3. [Full adb log (bigger than github allowed comment size)](https://gist.github.com/kainz/d22293d1213b85760a18) attached.

Is there anything else I can do to help you debug?

**Comment by moxie0** [comment]
Try again now?

**Comment by kainz** [comment]
New log, same deal: https://gist.github.com/kainz/674ead70507573328ee5

**Comment by kainz** [comment]
And with a clean TextSecure 2.23.3 reinstall: https://gist.github.com/kainz/d4d44928d6260461fafc

**Comment by moxie0** [comment]
How about now.  Hopefully it works, but at minimum it shouldn't crash your client anymore.

**Comment by kainz** [comment]
Correct, no more client crashes -- I see you are swapping the returned error (or maybe thats just my client being odd?) for a 413/throttled response.  Any ideas what my root issue could be? I can try and build/run some local git versions if you need to collect something else than the default exception data.

**Comment by moxie0** [comment]
@kainz Can you check again?  Sorry I don't have any way to reproduce this myself.

**Comment by kainz** [comment]
Works now! TYVM
